services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
      MONGO_INITDB_DATABASE: orgdb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
